"use client";
import { useState } from "react";

type A={icon:string;label:string;tone:string}; type S={name:string;activities:A[];choice?:"open"|"done"};
const W:{day:string;date:string;slots:S[]}[]=[
 {day:"Mo",date:"31",slots:[{name:"Morgen",activities:[{icon:"🏫",label:"Kita",tone:"sun"}]},{name:"Mittag",activities:[{icon:"🍝",label:"Nudeln",tone:"coral"}]},{name:"Nachmittag",activities:[{icon:"🚲",label:"Fahrrad",tone:"sky"},{icon:"🛒",label:"Einkaufen",tone:"mint"}]},{name:"Abend",activities:[{icon:"📖",label:"Vorlesen",tone:"lavender"}]}]},
 {day:"Di",date:"1",slots:[{name:"Morgen",activities:[{icon:"🏫",label:"Kita",tone:"sun"}]},{name:"Mittag",activities:[{icon:"🍲",label:"Suppe",tone:"coral"}]},{name:"Nachmittag",activities:[],choice:"open"},{name:"Abend",activities:[{icon:"🛁",label:"Baden",tone:"sky"}]}]},
 {day:"Mi",date:"2",slots:[{name:"Morgen",activities:[{icon:"🏫",label:"Kita",tone:"sun"}]},{name:"Mittag",activities:[{icon:"🥪",label:"Brotzeit",tone:"coral"}]},{name:"Nachmittag",activities:[{icon:"🛝",label:"Spielplatz",tone:"mint"},{icon:"🧁",label:"Backen",tone:"coral"}]},{name:"Abend",activities:[{icon:"🌙",label:"Schlafen",tone:"lavender"}]}]},
 {day:"Do",date:"3",slots:[{name:"Morgen",activities:[{icon:"🏫",label:"Kita",tone:"sun"}]},{name:"Mittag",activities:[{icon:"🍚",label:"Reis",tone:"coral"}]},{name:"Nachmittag",activities:[{icon:"🎨",label:"Basteln",tone:"lavender"}],choice:"done"},{name:"Abend",activities:[{icon:"📖",label:"Vorlesen",tone:"lavender"}]}]},
 {day:"Fr",date:"4",slots:[{name:"Morgen",activities:[{icon:"🏫",label:"Kita",tone:"sun"}]},{name:"Mittag",activities:[{icon:"🍕",label:"Pizza",tone:"coral"}]},{name:"Nachmittag",activities:[{icon:"👵",label:"Oma",tone:"lavender"}]},{name:"Abend",activities:[{icon:"🎬",label:"Film",tone:"sky"}]}]},
 {day:"Sa",date:"5",slots:[{name:"Morgen",activities:[{icon:"🦒",label:"Zoo",tone:"mint"}],choice:"done"},{name:"Mittag",activities:[{icon:"🥨",label:"Picknick",tone:"coral"}]},{name:"Nachmittag",activities:[{icon:"🏡",label:"Zuhause",tone:"sun"}]},{name:"Abend",activities:[{icon:"🛁",label:"Baden",tone:"sky"}]}]},
 {day:"So",date:"6",slots:[{name:"Morgen",activities:[{icon:"🥞",label:"Frühstück",tone:"sun"}]},{name:"Mittag",activities:[{icon:"🍝",label:"Familienessen",tone:"coral"}]},{name:"Nachmittag",activities:[{icon:"🌲",label:"Spaziergang",tone:"mint"}]},{name:"Abend",activities:[{icon:"🎒",label:"Kita packen",tone:"sky"}]}]}
];
function Card({a}:{a:A}){return <div className={`activity ${a.tone}`}><span>{a.icon}</span><small>{a.label}</small></div>}
function Board(){return <section className="board-shell"><div className="board-top"><div><p>Heute ist</p><h1>Mittwoch</h1></div><div className="time"><strong>15:32</strong><span>Nachmittag</span></div></div><div className="board-grid"><div className="time-labels"><span/><span>Morgen</span><span>Mittag</span><span>Nachmittag</span><span>Abend</span></div>{W.map((d,i)=><div className={`day-column ${i===2?"today":""} ${i<2?"past":""}`} key={d.day}><header><b>{d.day}</b><span>{d.date}</span></header>{d.slots.map(s=><div className={`slot ${i===2&&s.name==="Nachmittag"?"now":""}`} key={s.name}><div className="activities">{s.activities.map(a=><Card key={a.label} a={a}/>)}{s.choice==="open"&&<div className="choice open"><span>?</span><small>Du wählst</small></div>}{s.choice==="done"&&<div className="choice done"><small>ausgewählt</small></div>}</div></div>)}</div>)}</div><div className="board-footer"><span className="dot"/> Jetzt: <b>Spielplatz &amp; Backen</b><span className="footer-choice">Nächste Wahl: Dienstag Nachmittag</span></div></section>}
function Planner(){const[open,setOpen]=useState(true);return <section className="planner"><div className="planner-title"><div><p>Woche vom 31. Aug. – 6. Sept.</p><h2>Unser Wochenplan</h2></div><button className="add">+ Eintragen</button></div><div className="week-nav"><button>‹</button><strong>Diese Woche</strong><button>›</button></div><div className="planning-days">{W.slice(0,5).map((d,i)=><article className={i===2?"selected-day":""} key={d.day}><header><b>{["Montag","Dienstag","Mittwoch","Donnerstag","Freitag"][i]}</b><span>{d.date}. Sept.</span></header>{d.slots.map(s=><div className="plan-row" key={s.name}><span>{s.name}</span><div>{s.activities.map(a=><Card key={a.label} a={a}/>)}{s.choice==="open"&&<button className="plan-choice" onClick={()=>setOpen(!open)}>◌ Wahl offen</button>}{s.choice==="done"&&<button className="plan-choice done">✓ Wahl: Basteln</button>}</div></div>)}</article>)}</div>{open&&<aside className="choice-sheet"><button className="close" onClick={()=>setOpen(false)}>×</button><p>DIENSTAG · NACHMITTAG</p><h3>Was machen wir?</h3><div className="choice-options"><Card a={{icon:"🛝",label:"Spielplatz",tone:"mint"}}/><Card a={{icon:"🎨",label:"Basteln",tone:"lavender"}}/><Card a={{icon:"🚲",label:"Fahrrad",tone:"sky"}}/></div><button className="start-choice">Wahl am Board starten</button><small>Das Kind wählt eine Karte am Steckplatz aus.</small></aside>}</section>}
export default function Home(){const[v,setV]=useState<"board"|"plan">("board");return <main><nav><div className="brand"><span>●</span> wochenwerk</div><div><button className={v==="board"?"active":""} onClick={()=>setV("board")}>Board</button><button className={v==="plan"?"active":""} onClick={()=>setV("plan")}>Planen</button></div></nav>{v==="board"?<Board/>:<Planner/>}</main>}
